# 1D Array

In [3]:
import numpy as np

In [4]:
a = np.array([34,73,92,51,37,8])
a.dtype

dtype('int64')

In [5]:
a.size

6

In [6]:
a.shape

(6,)

In [7]:
a.ndim

1

In [8]:
a[0]

np.int64(34)

In [9]:
a[2]

np.int64(92)

# Multi dimensional array

In [10]:
a_2d = np.array([[12,37,46],[63,90,86]])
a_2d

array([[12, 37, 46],
       [63, 90, 86]])

In [11]:
a_2d.shape

(2, 3)

In [12]:
a_2d.ndim

2

In [13]:
a_2d.size

6

In [14]:
a_2d.dtype

dtype('int64')

In [15]:
a_2d[0]

array([12, 37, 46])

# Another type of multi dimensional array

In [16]:
a_3d = np.array([[[3,7,0]]])

In [17]:
a_3d

array([[[3, 7, 0]]])

In [18]:
a_3d.dtype

dtype('int64')

In [19]:
a_3d.shape

(1, 1, 3)

In [20]:
a_3d.size

3

In [21]:
a_3d.ndim

3

# Accessing elements in array

In [22]:
a_2d[0][1]

np.int64(37)

In [23]:
a_2d[1][2]

np.int64(86)

In [24]:
a_2d[0][0]

np.int64(12)

In [25]:
a_2d[1][1]

np.int64(90)

# Changing Datatype

In [26]:
a_2d =  np.array([[12,37,46],[63,90,86]], dtype = float)

In [27]:
a_2d

array([[12., 37., 46.],
       [63., 90., 86.]])

In [28]:
# a_2d.astype(float)

In [29]:
a_2d[0][1]

np.float64(37.0)

In [30]:
a_2d =  np.array([[12,37,46],[63,90,86]], dtype = int)

In [31]:
a_2d.astype(int)

array([[12, 37, 46],
       [63, 90, 86]])

In [32]:
a_2d

array([[12, 37, 46],
       [63, 90, 86]])

In [33]:
a_2d[0][1]

np.int64(37)

# Bigger Arrays

In [34]:
a_bigger = np.array([[[6,2,8,1],[1,7,3,6],[9,0,1,5]],[[1,3,5,8],[2,6,0,1],[2,1,6,8]],[[7,2,4,8],[2,0,1,4],[9,8,4,5]]],dtype = float)

In [35]:
a_bigger

array([[[6., 2., 8., 1.],
        [1., 7., 3., 6.],
        [9., 0., 1., 5.]],

       [[1., 3., 5., 8.],
        [2., 6., 0., 1.],
        [2., 1., 6., 8.]],

       [[7., 2., 4., 8.],
        [2., 0., 1., 4.],
        [9., 8., 4., 5.]]])

In [36]:
a_bigger.ndim

3

In [37]:
a_bigger.size

36

In [38]:
a_bigger.shape

(3, 3, 4)

In [39]:
a_bigger[2][1][3]

np.float64(4.0)

In [40]:
a_bigger[1][2][1]

np.float64(1.0)

In [41]:
a_bigger[0][1][2]

np.float64(3.0)

In [42]:
a_bigger[0][1]

array([1., 7., 3., 6.])

In [43]:
a_bigger[2][1]

array([2., 0., 1., 4.])

# Filling Arrays

In [44]:
a_full = np.full((3,4,5),8)

In [45]:
a_full

array([[[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]],

       [[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]],

       [[8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8],
        [8, 8, 8, 8, 8]]])

In [46]:
a_full.ndim

3

In [47]:
a_full.shape

(3, 4, 5)

In [48]:
a_full.size

60

In [49]:
b_full = np.full((3,5,4),15)

In [50]:
b_full

array([[[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]],

       [[15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15],
        [15, 15, 15, 15]]])

# Zeros and Ones

In [51]:
a_zero = np.zeros((2,4))

In [52]:
a_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
b_zero = np.zeros((4,3))

In [54]:
b_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
a_one = np.ones((2,3,4))

In [56]:
a_one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [57]:
a_one.ndim

3

In [58]:
b_one = np.ones((5,3))

In [59]:
b_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Empty and Random

In [60]:
a_empty = np.empty((4,7))

In [61]:
a_empty

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 7.56587584e-307, 1.37961302e-306,
        1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 8.90092016e-307, 1.02361342e-306,
        6.89804133e-307],
       [8.90104239e-307, 8.90098127e-307, 8.90111708e-307,
        6.23054633e-307, 8.90111708e-307, 6.89806849e-307,
        8.90104239e-307],
       [1.42417221e-306, 1.95820216e-306, 1.24611741e-306,
        1.33511562e-306, 1.11261570e-306, 1.42410974e-306,
        1.42410974e-306]])

In [62]:
a_random = np.random.random((2,2))

In [63]:
a_random

array([[0.2082953 , 0.09329664],
       [0.15476368, 0.11487361]])

In [64]:
a_random.ndim

2

In [65]:
a_random.size

4

In [66]:
a_random.shape

(2, 2)

# Range : Arange

In [67]:
a_range = np.arange(2,50,3)

In [68]:
a_range

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [69]:
a_range.ndim

1

In [70]:
a_range.size

16

In [71]:
a_range.shape

(16,)

In [72]:
b_range = np.arange(1,20,2)

In [73]:
b_range

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [74]:
c_range = np.arange(0,30,2)
c_range

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

# Range : Linspace

In [75]:
a_linspace = np.linspace(0,30,20)

In [76]:
a_linspace

array([ 0.        ,  1.57894737,  3.15789474,  4.73684211,  6.31578947,
        7.89473684,  9.47368421, 11.05263158, 12.63157895, 14.21052632,
       15.78947368, 17.36842105, 18.94736842, 20.52631579, 22.10526316,
       23.68421053, 25.26315789, 26.84210526, 28.42105263, 30.        ])

In [77]:
a_linspace = np.linspace(0,50,20 , dtype = int)

In [78]:
a_linspace

array([ 0,  2,  5,  7, 10, 13, 15, 18, 21, 23, 26, 28, 31, 34, 36, 39, 42,
       44, 47, 50])

In [79]:
a_linspace.size

20

In [80]:
a_linspace = np.linspace(0,30,2)

In [81]:
a_linspace 

array([ 0., 30.])

In [82]:
a_linspace.ndim

1

In [83]:
b_linspace = np.linspace(1,10,5)

In [84]:
b_linspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Identity

In [85]:
a_identity = np.identity(6)

In [86]:
a_identity 

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [87]:
a_identity = np.eye(4)

In [88]:
a_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Math Functions 

In [89]:
a

array([34, 73, 92, 51, 37,  8])

In [90]:
np.exp(a)

array([5.83461743e+14, 5.05239363e+31, 9.01762841e+39, 1.40934908e+22,
       1.17191424e+16, 2.98095799e+03])

In [91]:
np.sqrt(a)

array([5.83095189, 8.54400375, 9.59166305, 7.14142843, 6.08276253,
       2.82842712])

In [92]:
np.sin(a)

array([ 0.52908269, -0.67677196, -0.77946607,  0.67022918, -0.64353813,
        0.98935825])

In [93]:
np.cos(a)

array([-0.84857027, -0.73619272, -0.62644445,  0.7421542 ,  0.76541405,
       -0.14550003])

In [94]:
np.tan(a)

array([-0.62349896,  0.9192864 ,  1.24427006,  0.90308615, -0.84077126,
       -6.79971146])

In [95]:
np.log(a)

array([3.52636052, 4.29045944, 4.52178858, 3.93182563, 3.61091791,
       2.07944154])

In [96]:
np.abs(a)

array([34, 73, 92, 51, 37,  8])

# Aggregate Functions

In [97]:
a.sum()

np.int64(295)

In [98]:
a.min()

np.int64(8)

In [99]:
a.max()

np.int64(92)

In [100]:
a.mean()

np.float64(49.166666666666664)

In [101]:
np.median(a)

np.float64(44.0)

In [102]:
np.std(a)

np.float64(27.3216438418742)

In [103]:
np.sum(a)

np.int64(295)

In [104]:
np.var(a)

np.float64(746.4722222222223)

In [105]:
np.argmin(a)

np.int64(5)

In [106]:
np.argmax(a)

np.int64(2)