# Numpy Task

1.a)

In [79]:
import numpy as np

In [80]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

b)

In [81]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

c)

In [82]:
a.dtype

dtype('int64')

In [83]:
a.shape

(4, 5)

In [84]:
a.size

20

2.a)

In [85]:
a = np.array([10,20,30,40,50,60,70,80,90,100])
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [86]:
print(a[::2])

[10 30 50 70 90]


b)

In [87]:
a[2:7]

array([30, 40, 50, 60, 70])

c)

In [88]:
a[::-1]

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

d)

In [89]:
a[4] = 500
a

array([ 10,  20,  30,  40, 500,  60,  70,  80,  90, 100])

3.a)

In [90]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [91]:
b = a.copy()

In [92]:
c = a.view()

In [93]:
b[0] = 100
print(b)
print(a)

[100  20  30  40  50]
[10 20 30 40 50]


In [94]:
c[0] = 500
print(c)
print(a)

[500  20  30  40  50]
[500  20  30  40  50]


4.a)

In [95]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [96]:
np.hstack(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

b)

In [97]:
ar = np.arange(1,10).reshape(1,9)
ar

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

c)

In [98]:
arr.shape

(3, 3)

In [99]:
ar.shape

(1, 9)

5.a)

In [100]:
ara = np.array([[30,10,20],
                [60,40,50],
                [90,70,80]])
ara

array([[30, 10, 20],
       [60, 40, 50],
       [90, 70, 80]])

In [101]:
np.sort(ara)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

b)

6.a)

In [102]:
a = np.array([10,25,30,45,50,65,70,85])
a

array([10, 25, 30, 45, 50, 65, 70, 85])

In [103]:
print(np.where(a == 50))

(array([4]),)


b)

In [104]:
print(np.where(a >= 50))


(array([4, 5, 6, 7]),)


c)

In [105]:
print(np.where(a % 5))

(array([], dtype=int64),)


7.a)

In [106]:
a = np.array([45,78,92,56,34,88,67,95,41,73])
a

array([45, 78, 92, 56, 34, 88, 67, 95, 41, 73])

In [107]:
print(a[a > 60])

[78 92 88 67 95 73]


b)

In [108]:
a = np.array([45,78,92,56,34,88,67,95,41,73])
print(a[(a >= 50) & (a <= 80)])

[78 56 67 73]


c)

In [109]:
print(a[a >= 90])

[92 95]


8.a)

In [110]:
a = np.array([12,25,38,41,56,63,74,89])
a

array([12, 25, 38, 41, 56, 63, 74, 89])

In [111]:
print(a + 10)

[22 35 48 51 66 73 84 99]


b)

In [112]:
print(a * 2)

[ 24  50  76  82 112 126 148 178]


c)

In [113]:
print((a[a % 2 == 0]) ) 
print(a[a > 40])

[12 38 56 74]
[41 56 63 74 89]


d)

9.a)

In [114]:
b = np.array([25,40,35,60,50,75,45,90,55,65])
b

array([25, 40, 35, 60, 50, 75, 45, 90, 55, 65])

In [115]:
print(np.mean(b))
print(np.median(b))
print(np.std(b))
print(np.min(b))
print(np.max(b))
print(np.sum(b))


54.0
52.5
18.411952639521967
25
90
540


b)

In [116]:
print(np.argmin(b))
print(np.argmax(b))

0
7


10.a)

In [117]:
sales = np.array([[1200,1500,1100,1800],
                 [2000,1700,1600,2100],
                  [900,1300,1250,1400]])
sales

array([[1200, 1500, 1100, 1800],
       [2000, 1700, 1600, 2100],
       [ 900, 1300, 1250, 1400]])

In [118]:
np.sum(sales , axis=1)

array([5600, 7400, 4850])

b)

In [119]:
np.sum(sales , axis=0)

array([4100, 4500, 3950, 5300])

c)

In [120]:
np.max(sales)

np.int64(2100)

d)

In [121]:
np.argmax(sales)

np.int64(7)

e)

In [122]:
np.sort(sales)

array([[1100, 1200, 1500, 1800],
       [1600, 1700, 2000, 2100],
       [ 900, 1250, 1300, 1400]])

f)

In [123]:
sales[sales > 1500]

array([1800, 2000, 1700, 1600, 2100])

g)

In [124]:
sales.flatten()

array([1200, 1500, 1100, 1800, 2000, 1700, 1600, 2100,  900, 1300, 1250,
       1400])