# 1.

In [41]:
import numpy as np
a = np.array([10,20,30,40,50])

In [42]:
a

array([10, 20, 30, 40, 50])

In [43]:
a.shape

(5,)

In [44]:
a.dtype

dtype('int64')

In [45]:
a.size

5

In [46]:
a.nbytes

40

# 2.

In [47]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
b[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3.

In [49]:
c = np.arange(1,13).reshape(3,4)
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 4.

In [50]:
d = np.array([10,20,30])
d

array([10, 20, 30])

In [51]:
e = np.array([40,50,60])
e

array([40, 50, 60])

In [52]:
np.vstack((d,e))

array([[10, 20, 30],
       [40, 50, 60]])

# 5.

In [53]:
f = np.array([10,20,30,40,50])
f

array([10, 20, 30, 40, 50])

In [54]:
np.array_split(f,3)

[array([10, 20]), array([30, 40]), array([50])]

# 6.

In [55]:
g = np.array([5,10,15,20,25,30])
g

array([ 5, 10, 15, 20, 25, 30])

In [56]:
np.where(g > 15)

(array([3, 4, 5]),)

# 7.

In [57]:
arr = np.array([12,5,20,8,30,15])
arr

array([12,  5, 20,  8, 30, 15])

In [58]:
result = arr[(arr>=10) & (arr<=25)]
result

array([12, 20, 15])

# 8.

In [59]:
k = np.array([4,9,16,25])
k

array([ 4,  9, 16, 25])

In [60]:
np.sqrt(k)

array([2., 3., 4., 5.])

# 9.

In [61]:
i = np.array([1,2,3,4])
i

array([1, 2, 3, 4])

In [62]:
np.exp(i)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [63]:
np.log(i)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

# 10.

In [64]:
j = np.array([10,20,30,40,50])
j

array([10, 20, 30, 40, 50])

In [65]:
print(np.sum(j))
print(np.average(j))
print(np.median(j))
print(np.std(j))
print(np.var(j))
print(np.min(j))
print(np.max(j))

150
30.0
30.0
14.142135623730951
200.0
10
50


# 11.

In [66]:
k = np.array([10,20,5,40,15])
k

array([10, 20,  5, 40, 15])

In [67]:
print(np.argmin(k))
print(np.argmax(k))

2
3


# 12.

In [68]:
x = np.array([[2,4,6],[8,10,12]])
x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [69]:
np.sum(x ,axis=1)

array([12, 30])

In [70]:
np.sum(x ,axis=0)

array([10, 14, 18])

# 13.

In [71]:
org = np.array([10,20,30,40])
org

array([10, 20, 30, 40])

In [72]:
cpy = org.copy()

In [73]:
viw = org.view()

In [74]:
cpy[0] = 100
print(cpy)
print(org)

[100  20  30  40]
[10 20 30 40]


In [75]:
viw[0] = 20
print(viw)
print(org)

[20 20 30 40]
[20 20 30 40]


# 14.

In [77]:
print(np.random.rand(5))
print(np.random.randint(1,21,5))
print(np.random.choice([10,20,30,40],5))      

[0.37971613 0.59316872 0.32881558 0.38059569 0.94434186]
[ 4 10  9 14  9]
[30 40 10 20 10]


# 15.

In [78]:
v = np.arange(1,7).reshape(2,3)
v

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
for i in np.nditer(v) :
    print(i)
result = v.flatten()
print(result)

1
2
3
4
5
6
[1 2 3 4 5 6]


# 16.

In [87]:
q = np.array([35,10,60,25,5,45])
q

array([35, 10, 60, 25,  5, 45])

In [88]:
np.sort(q)

array([ 5, 10, 25, 35, 45, 60])

In [89]:
np.sort(q)[::-1]

array([60, 45, 35, 25, 10,  5])

# 17.

In [90]:
array = ["Mango","Apple","Grapes","Banana","Orange"]
array

['Mango', 'Apple', 'Grapes', 'Banana', 'Orange']

In [91]:
np.sort(array)

array(['Apple', 'Banana', 'Grapes', 'Mango', 'Orange'], dtype='<U6')

# 18.

In [92]:
u = np.array([10,20,30,40,50,60])
u

array([10, 20, 30, 40, 50, 60])

In [93]:
np.array_split(u,4)

[array([10, 20]), array([30, 40]), array([50]), array([60])]

# 19.

In [94]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
np.hstack(arr)

array([1, 2, 3, 4, 5, 6])

# 20.

In [99]:
num1 = np.array([10,20,30,40,50])
num1

array([10, 20, 30, 40, 50])

In [100]:
num2 = np.array([60,70,80,90,100])
num2

array([ 60,  70,  80,  90, 100])

In [106]:
print("Addition is :",num1 + num2)
print("Subtraction is :",num1 - num2)
print("Product is :",num1 * num2)
print("Division is :",num1 / num2)
print("Squaring is :",num1 ** num2)

Addition is : [ 70  90 110 130 150]
Subtraction is : [-50 -50 -50 -50 -50]
Product is : [ 600 1400 2400 3600 5000]
Division is : [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Squaring is : [1152921504606846976                   0                   0
                   0                   0]
