# Special Arrays :

In [10]:
import numpy as np
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# Array Ranges :

# Logspace

In [9]:
np.logspace(1,3,5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

# Random Module :

In [14]:
np.random.seed(0)

In [19]:
np.random.rand(5)

array([0.47360042, 0.18633234, 0.73691818, 0.21655035, 0.13521817])

In [16]:
np.random.randint(1,10,5)

array([4, 1, 4, 6, 1], dtype=int32)

In [17]:
np.random.randn(5)

array([-0.4530558 ,  1.49407907, -0.20515826,  0.3130677 , -0.85409574])

In [22]:
np.random.choice([10,20,30],5)

array([30, 10, 20, 20, 20])

# Indexing :

# 1D Array

In [27]:
a = np.array([10,20,30,40])
a[1]

np.int64(20)

In [28]:
a[0]

np.int64(10)

# 2D Array

In [29]:
a = np.array([[20,30],[10,50]])

In [32]:
a[1,1]

np.int64(50)

# 3D Array

In [41]:
a = np.array([[[1,4],[6,3]],
              [[9,7],[1,3]]])
a

array([[[1, 4],
        [6, 3]],

       [[9, 7],
        [1, 3]]])

In [44]:
a[0,1,0]

np.int64(6)

# Slicing :

In [45]:
a = np.array([[1,3,5,7,9],[2,3,5,7,1],[3,5,7,2,9]])
a

array([[1, 3, 5, 7, 9],
       [2, 3, 5, 7, 1],
       [3, 5, 7, 2, 9]])

In [46]:
a[1:2]

array([[2, 3, 5, 7, 1]])

In [47]:
a[1:3]

array([[2, 3, 5, 7, 1],
       [3, 5, 7, 2, 9]])

In [48]:
a[:,1]

array([3, 3, 5])

In [49]:
a[0:2,1:]

array([[3, 5, 7, 9],
       [3, 5, 7, 1]])

# Iterating Arrays :

# 1D Array

In [54]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [57]:
for x in a:
  print(x)

1
2
3


# 2D Array

In [58]:
a = np.array([[1,2],[5,8]])
a

array([[1, 2],
       [5, 8]])

In [59]:
for x in a:
    print(x)

[1 2]
[5 8]


# Using nditer()

In [60]:
for x in np.nditer(a):
    print(x)

1
2
5
8


# Copy vs View :

In [61]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [75]:
b = a.copy()
c = a.view()

In [67]:
b

array([1, 2, 3])

In [68]:
c

array([1, 2, 3])

In [71]:
b[0] = 100
b

array([100,   2,   3])

In [72]:
a

array([1, 2, 3])

In [73]:
c[0]= 25
c

array([25,  2,  3])

In [74]:
a

array([25,  2,  3])

# Reshape :

In [76]:
a = np.arange(6)
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

# Flatten

In [77]:
a = np.array([[1,2,3],[4,5,6]])
a.flatten()

array([1, 2, 3, 4, 5, 6])

# Ravel

In [78]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

# Joining Arrays :

In [79]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a

array([1, 2, 3])

In [80]:
b

array([4, 5, 6])

# Concatenate

In [81]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Stack

In [82]:
np.stack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

# Vstack

In [83]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

# hstack

In [84]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

# Splitting Arrays :

In [85]:
a = np.array([1,2,3,4,5,6])
np.split(a,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [86]:
np.split(a,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [88]:
np.vsplit(a.reshape(2,3),2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

# Sorting :

In [89]:
a = np.array([3,1,4,1,5])
np.sort(a)

array([1, 1, 3, 4, 5])

In [90]:
a = np.array([[3,1],[6,4]])
np.sort(a,axis=0)

array([[3, 1],
       [6, 4]])

# Searching :

In [91]:
a = np.array([1,3,5,7,5])
np.where(a==5)

(array([2, 4]),)

In [92]:
a = np.array([1,3,5,7,5])
np.searchsorted(a,4)

np.int64(2)

# Filtering :

In [93]:
a = np.array([1,3,5,7,5,4,8,9,6])
a[a > 5]

array([7, 8, 9, 6])

In [94]:
a[a % 2 == 0]

array([4, 8, 6])

# Array Mathematics :

In [95]:
a = np.array([10,20,30])
b = np.array([1,2,3])
a + b

array([11, 22, 33])

In [96]:
a - b

array([ 9, 18, 27])

In [100]:
a * 2

array([20, 40, 60])

In [101]:
a / 2

array([ 5., 10., 15.])

In [102]:
a ** 2

array([100, 400, 900])

# Axis Concept :

In [103]:
a = np.array([[1,2,3],[4,5,6]])
np.sum(a, axis=0) # column wise

array([5, 7, 9])

In [104]:
np.sum(a, axis=1) #row wise

array([ 6, 15])