In [24]:
import numpy as np

In [25]:
a = np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [26]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
a = np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [28]:
a = np.arange(1,21,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [30]:
a = np.ones(6)
a          

array([1., 1., 1., 1., 1., 1.])

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a = np.linspace(0,10,5)
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
a = np.array([5,10,15,20,25])
a[0]

np.int64(5)

In [35]:
a = np.array([10,20,30,40,50])
a[2:]

array([30, 40, 50])

In [36]:
a = np.arange(1,11)
a[a > 5]

array([ 6,  7,  8,  9, 10])

In [37]:
a = np.arange(1,11)
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [38]:
a = np.array([10,20,30,40,50])
a.max()

np.int64(50)

In [39]:
a = np.array([10,20,30,40,50])
a.min()

np.int64(10)

In [40]:
a = np.array([10,20,30,40,50])
a.sum()

np.int64(150)

In [41]:
a = np.array([10,20,30,40,50])
a.mean()

np.float64(30.0)

In [42]:
a = np.array([5,2,8,1,9])
np.sort(a)

array([1, 2, 5, 8, 9])

In [43]:
a = np.array([10,20,30,40,50])
np.argmax(a)

np.int64(4)

In [44]:
a = np.array([10,20,30,40,50])
np.argmin(a)

np.int64(0)